### ISSUE TITLE
socket.SafeHandle is not defined

### ISSUE THREAD

**Issue by richardschneider** [tmds/Tmds.LibC#28]
I am trying to use the [socket example](https://github.com/tmds/Tmds.LibC#example-1-socket-extension-method-to-set-raw-socket-options).  Getting an error on the following line

```csharp    
    SafeHandle handle = socket.SafeHandle;
```
error CS1061: 'Socket' does not contain a definition for 'SafeHandle' and no accessible extension method 'SafeHandle' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?)

What am I missing?

**Comment by tmds** [comment]
The Socket.SafeHandle property is only exposed from .NET Core 3.0 onwards.
It should work if you use one of the 3.0 preview releases.
