### ISSUE TITLE
Example 3 in README is wrong

### ISSUE THREAD

**Issue by jkotas** [tmds/Tmds.LibC#31]
This code is wrong:

```
 string path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        fixed (byte* pathname = Encoding.UTF8.GetBytes(path))
        {
            int rv = mkdir(pathname, S_IRWXU);
```

`Encoding.UTF8.GetBytes` does not create zero-terminated string. The byte that follows the converted UTF8 string can belong to the next object and it is not guaranteed to be zero.

**Comment by tmds** [comment]
Thanks for reporting this!
