### ISSUE TITLE
Value not accessible for mode_t

### ISSUE THREAD

**Issue by seertenedos** [tmds/Tmds.LibC#34]
mode_t's Value is not accessible if you need to pass libraries you don't want tied to this library and struct.  This could be the same if other structs and should be fixed but in the case of this one you have an implicit operator in from a ushort but you can only get it out as a string then parse that to a ushort. 

If there is an implicit operator in can you add one out or a method to get the Value out that is public not internal?  I really need this for your fuse library.

**Comment by seertenedos** [comment]
At the minute i use the following as a work around but it is hardly efficient or a good solution.
ushort.Parse(mode.ToString())

**Comment by tmds** [comment]
Let's add an explicit operator to cast to ushort.
@seertenedos Do you want to make a PR for it?

**Comment by seertenedos** [comment]
sorry for the delay. added https://github.com/tmds/Tmds.LibC/pull/35 
I would prefer not to do a (ushort) infront of a uint but could not think of a nice simple way

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/Tmds.LibC/pull/36

**Comment by tmds** [comment]
@seertenedos this is part of the 0.3.0 version which is on nuget.org.

**Comment by seertenedos** [comment]
Thanks
