### ISSUE TITLE
sockaddr_ll

### ISSUE THREAD

**Issue by massoudasadi** [tmds/Tmds.LibC#38]
can you add sockaddr_ll struct ?

**Comment by tmds** [comment]
hi @massoudasadi I'll take a look into it. It may take some time.

**Comment by tmds** [comment]
Added in https://github.com/tmds/Tmds.LibC/pull/40.

**Comment by massoudasadi** [comment]
thanks @tdms

**Comment by massoudasadi** [comment]
thanks @tmds
