### ISSUE TITLE
Support for dotnetcore 3.1

### ISSUE THREAD

**Issue by bmigette** [tmds/Tmds.LibC#48]
This nuget package does not seem to support dotnetcore 3.1.

Getting following exception when running my projet:
`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Tmds.LibC, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Tmds.LibC, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'

Press any key to continue...
`

**Comment by tmds** [comment]
The library supports .NET Core 2.0 and higher, so also 3.1.
The error says the dll is missing.
Can you provide some steps to reproduce the issue?

**Comment by bmigette** [comment]
Hi, I just added Tmds.Libc to my project using Nuget packet manager, nothing more.
I am using visual Studio 8.5.1 on Mac.

**Comment by tmds** [comment]
> on Mac

This package doesn't support mac.

The bindings are for Linux.

**Comment by bmigette** [comment]
Too bad, libc is also present on macos, this could be useful :)
