### ISSUE TITLE
ioctl request unsigned long

### ISSUE THREAD

**Issue by vindicatorr** [tmds/Tmds.LibC#57]
Shouldn't the ioctl "request" be "long" instead of "int"?
`int ioctl(int fd, unsigned long request, ...);` *ioctl.2

I only ask because my bluetooth marshalling for `#define RFCOMMGETDEVINFO        _IOR('R', 211, int)` causes the int to overflow to -2147200301.

**Comment by tmds** [comment]
The overflow should be fine.
It gets passed as a long to the kernel in https://github.com/tmds/Tmds.LibC/blob/master/src/Sources/linux.specific/ioctl.sizet.cs.

**Comment by vindicatorr** [comment]
I have no idea why it "should be fine". Aren't an overflowed int != it's long counterpart?
I just made a couple of quick tests in C and C# and the values are certainly different:
C
```
long test_long = RFCOMMGETDEVLIST; //2147766994
int test_int = RFCOMMGETDEVLIST; //-2147200302

long libfunc(long p)
{
    return p;
}
```
C#
```
[System.Runtime.InteropServices.DllImport(dllName: "libtest.so.1", SetLastError = true)]
public static extern long libfunc(int parg);

unsafe {
    long test_long = (long)2 << 30;
    System.Diagnostics.Debug.WriteLine(test_long); //2147483648
    System.Diagnostics.Debug.WriteLine(libfunc((int)test_long)); //-2147483648 because once casted, it overflows because it can't fit within the max size.
}
```
So once you have to cast to "int" for "public static int ioctl(int fd, int request)", the value completely changes if the size is larger than the max int.

**Comment by tmds** [comment]
https://github.com/tmds/Tmds.LibC/issues/57 should fix the issue.

**Comment by tmds** [comment]
Please give it a try using the NuGet feed mentioned in the README and let me know if it works.
