### ISSUE TITLE
Example of working ioctl call

### ISSUE THREAD

**Issue by Veverke** [tmds/Tmds.LibC#63]
Hi Tom,
I am struggling in trying to perform a successful ioctl call from a .net app running on Linux.
I have been trying things such as [this](https://stackoverflow.com/q/68738429/1219280).

I found this repository. Have tried using your 3rd ioctl overload (with void* parameter). Nothing yet.
Would you be able to provide a snippet of a successful ioctl call ? 
Specifically, I am interested in getting range info out of network driver (one of the available network interfaces in the machine should have an ioctl call returning a value greater than zero).
For instance, if I debug the code from [wireless_tools](https://github.com/HewlettPackard/wireless-tools) (function iw_get_range_info), the iw_get_ext (which calls ioctl) will return 0 for one of the interfaces. But I am unable to do the same in C#, all interfaces keep returning -1. And I can't benefit from using explain_ioctl (2nd link above).

Do you have a working successful ioctl call for request number 0x8B0B (35595) ?

**Comment by tmds** [comment]
@Veverke can you share a small program that captures what you are trying to do?

**Comment by Veverke** [comment]
Thanks a lot for responding!
Here is a gist with a demo sample app. Program.cs has the calls to ioctl I have been trying, without success.
https://gist.github.com/Veverke/325e9119ae2779a3eebaca3f1a3af97a

**Comment by tmds** [comment]
`strace` will show you the error codes.

You can also use `iwlist` (and other tools) with `strace` to verify the `ioctl` are expected to work.

For the app you shared:
```
$ strace -qq -f -e socket,ioctl ./console
[pid 23652] socket(AF_UNIX, SOCK_STREAM, 0) = 3
[pid 23651] socket(AF_UNIX, SOCK_STREAM, 0) = 3
[pid 23650] socket(AF_UNIX, SOCK_STREAM, 0) = 8
[pid 23650] socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 17
[pid 23650] ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 23650] ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 23650] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 23650] ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
Opened socket: [17]
[pid 23650] socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 26
[pid 23650] ioctl(17, _IOC(_IOC_NONE, 0xb9, 0xe9, 0x296), 0x7ffd337133c0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 23650] ioctl(17, SIOCGIWRANGE, 0x7ffd337133c0) = -1 ENODEV (No such device)
ioctl result: [-1]
[pid 23650] ioctl(17, SIOCGIWRANGE, 0x7f85e83ee160) = -1 ENODEV (No such device)
ioctl result (SWIG): [-1]
[pid 23650] ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
[pid 23650] ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
```

For example, `ENODEV` tells you it doesn't know what device you are referring to.

Your `iwreq` looks like:
```
    public struct iwreq
    {
        public string ifrn_name;
        public iwreq_data u;

        public void init()
        {
            ifrn_name = string.Empty;
            u.init();
        }
    }
```

The Linux one looks like:
```
struct iwreq {
        union
        {
                char    ifrn_name[IFNAMSIZ];    /* if name, e.g. "eth0" */
        } ifr_ifrn;

        /* Data part (defined just above) */
        union iwreq_data        u;
};
```
You need to marshal the interface name in a fixed size array.

**Comment by Veverke** [comment]
running `strace -qq -f -e socket,ioctl iwlist scanning` gives the following trace:
```
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
ioctl(3, SIOCGIWRANGE, 0x7ffcd8bbe300)  = -1 EOPNOTSUPP (Operation not supported)
enp4s0    Interface doesn't support scanning.

ioctl(3, SIOCGIWRANGE, 0x7ffcd8bbe300)  = -1 EOPNOTSUPP (Operation not supported)
docker0   Interface doesn't support scanning.

ioctl(3, SIOCGIWRANGE, 0x7ffcd8bbe300)  = -1 EOPNOTSUPP (Operation not supported)
lo        Interface doesn't support scanning.

ioctl(3, SIOCGIWRANGE, 0x7ffcd8bbe300)  = 0
ioctl(3, SIOCSIWSCAN, 0x7ffcd8bbe840)   = -1 EPERM (Operation not permitted)
ioctl(3, SIOCGIWSCAN, 0x7ffcd8bbe840)   = 0
wlp5s0    Scan completed :

```
and goes on to print the output for wlp5s0.

Leaving my C# code aside a while, from an ioctl call point of view, the very same ioctl call is performed on the 3 different network interfaces. Why is it that only a specific call from all the calls above returns 0 ? The arguments are the very same for all calls. 
I mean how does the differentiation between interfaces happens at ioctl level ? Or it does not ? Or it is in at a hardware level ?

**Comment by tmds** [comment]
This question was answered. Closing.
