### ISSUE TITLE
Error constants should be compile time constants

### ISSUE THREAD

**Issue by ramon-garcia** [tmds/Tmds.LibC#70]
As of now, error constants such as EACCESS are runtime values, and so they cannot be used in switch/case.

Please consider placing then in an enum

Also consider a function to translate exception codes to .NET Exceptions (for instance ENOFILE -> FileNotFoundException())

**Comment by tmds** [comment]
> Please consider placing then in an enum

They can't be an enum because they can be different depending on the platform.

Unfortunately, that makes them unusable in a switch case.

> Also consider a function to translate exception codes to .NET Exceptions (for instance ENOFILE -> FileNotFoundException())

The scope of the library is to to provide raw libc functions and stay as close to the native signatures as possible. Anything else is not in scope.
